# Simplest possible Ingress, which sets up a Google Cloud LB (see ingress.class)
# The spec may have many more rules for routing, load balancing, TLS, and so forth
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Use "gce" for GKE's ingress controller
spec:
#  tls:
#    - hosts:
#        - localhost
#      secretName: hello-kubernetes-tls
  rules:
    - http:
        paths:
          - path: / # Use "/*" for GKE
            pathType: Prefix # Use "ImplementationSpecific" for GKE
            backend:
              service:
                name: frontend-nodejs
                port:
                  number: 80