kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-golang
  labels:
    group: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-golang-pod
  template:
    metadata:
      labels:
        app: backend-golang-pod
    spec:
      containers:
        - name: backend-golang-container
          image: mouton4711/kubernetes:backend-golang
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: translation-config
---
kind: Service
apiVersion: v1
metadata:
  name: backend-golang
spec:
  selector:
    app: backend-golang-pod
  ports:
    - name: http-backend-golang-port
      port: 80
      targetPort: 8080
