apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - target:
      kind: Deployment
      group: hello-kubernetes # Exclude Redis from patching
    patch: |-
      - op: replace
        path: /spec/template/metadata/labels/env
        value: green

# Generate a translation config from literals
configMapGenerator:
  - name: translation-config
    literals:
      - greetingLabel=[GREEN] Hola
