kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-nodejs
  labels:
    group: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nodejs-pod
  template:
    metadata:
      labels:
        app: frontend-nodejs-pod
    spec:
      containers:
        - name: frontend-nodejs-container
          image: mouton4711/hello_k8s_frontend-nodejs
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: translation-config
          env:
            - name: BACKEND_HOSTS
              value: "backend-golang,backend-rust,backend-spring"
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-nodejs
spec:
  ports:
    - name: http-service-port
      port: 80
      targetPort: 8080
  selector:
    app: frontend-nodejs-pod
  type: LoadBalancer
# loadBalancerIP: 0.0.0.0 # bind the LB created by the cloud provider to a static address
