kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-nodejs
  labels:
    group: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nodejs-pod
  template:
    metadata:
      labels:
        app: frontend-nodejs-pod
    spec:
      containers:
        - name: frontend-nodejs-container
          image: mouton4711/kubernetes:frontend-nodejs
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: translation-config
          env:
            - name: BACKEND_HOST1
              value: "backend-golang"
            - name: BACKEND_HOST2
              value: "backend-spring"
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-nodejs
spec:
  ports:
    - name: http-service-port
      port: 80
      targetPort: 8080
  selector:
    app: frontend-nodejs-pod
  type: LoadBalancer
